name: "Github Release"
author: "Erwin Seribo"
branding:
  icon: "git-branch"
  color: "gray-dark"
description: "Publish Github releases from an action"

inputs:
  release_args:
    required: true
    type: string

runs:
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Release
      run: echo 'testing from action'
      shell: bash
