name: "Release Phase 1"

on:
  schedule:
    - cron: '*/3 * * * *'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: 'Release Phase 1: ascenda_go/nexus'
        working-directory: ./
        run: echo 'first'