name: "Release Phase 3"

on:
  # workflow_run:
  #   workflows: ["Release Phase 2"]
  #   types:
  #     - completed
  # schedule:
  #   - cron: '* * * * *'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: 'Release Phase 3: anz/vma'
        working-directory: ./
        run: echo 'third'