name: "Release Phase 3"

on:
  # workflow_run:
  #   workflows: ["Release Phase 2"]
  #   types:
  #     - completed
  # schedule:
  #   - cron: '* * * * *'
  push

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Test
        working-directory: ./
        run: echo 'third'
      - uses: rewin0087/test_github_actions@master
        with:
          release_args: -h 0
          app: Test
