name: "Release Phase 1"

on:
  schedule:
    - cron: '* * * * *'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: 'Release Phase 1: ascenda_go/nexus'
        working-directory: ./
        run: echo 'first'