name: "Release Phase 1"

on:
  # workflow_run:
  #   workflows: ["Release Phase 2"]
  #   types:
  #     - completed
  # schedule:
  #   - cron: '* * * * *'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: 'Release Phase 1: ascenda_go/nexus'
        working-directory: ./
        run: echo 'first'