name: "Release Phase 2"

on:
  workflow_run:
    workflows: ["Release Phase 1"]
    types:
      - completed
  schedule:
    - cron: '*/2 * * * *'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: 'Release Phase 2: westpac/fab/hyundai'
        working-directory: ./
        run: echo 'second'