name: "Release Phase test"

on:
  workflow_call:
    inputs:
      release_args:
        required: true
        type: string
    secrets:
      workflow_token:
        required: true

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repo 📚
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: rewin0087/test_github_actions
      - name: Test
        working-directory: ./
        run: echo 'third'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm install
        shell: bash
        env:
          BUNDLE_GEMS__CONTRIBSYS__COM: ${{ secrets.SIDEKIQ_PRO_PASSWORD }}
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: "hieuk09:${{ secrets.GIT_GITHUB_COM_PASSWORD }}"
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.GIT_GITHUB_COM_PASSWORD }}
          GITHUB_PKG_REG_TOKEN: ${{ secrets.GIT_GITHUB_COM_PASSWORD }}
      - name: Release
        run: |
          node ./index.js ${{ inputs.release_args }} --run
          echo test ${{ secrets.SIDEKIQ_PRO_PASSWORD }}
        shell: bash